route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: "${TOMAIL}"
    from: "${FROMMAIL}"
    smarthost: mail.berndklaus.at:587
    auth_username: "${FROMMAIL}"
    auth_identity: "${FROMMAIL}"
    auth_password: "${PASSWORD}"
