version: '2'
services:
  wordpress:
      image: wordpress
      links:
       - mariadb:mysql
      environment:
       - WORDPRESS_DB_USER=wordpress
       - WORDPRESS_DB_PASSWORD=${PASSWORD}
       - VIRTUAL_HOST=berndklaus.at
       - LETSENCRYPT_HOST=berndklaus.at
       - LETSENCRYPT_EMAIL=admin@berndklaus.at
      expose:
       - "8080/tcp"
      volumes:
       - ./code:/code
       - ./html:/var/www/html
      restart: always
      networks:
       - proxy
       - default

  mariadb:
      image: mariadb
      environment:
       - MYSQL_ROOT_PASSWORD=${PASSWORD}
       - MYSQL_DATABASE=wordpress
       - MYSQL_USER=wordpress
       - MYSQL_PASSWORD=${PASSWORD}
      volumes:
       - ./mysql:/var/lib/mysql
      restart: always

networks:
  default:
    driver: bridge
  proxy:
    external:
       name: proxy


